spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    defer-datasource-initialization: true
  datasource:
    url: jdbc:mysql://localhost:3306/viceversa
    username:
    password:
  sql:
    init:
      mode: always
